### PR TITLE
fetch before updating checkouts

### PR DESCRIPTION
**Pull request by weissi**
hey @milseman I'm not sure if this should be needed but `utils/update-checkouts` doesn't actually seem to fetch the remotes 🤔.

### CODE REVIEW

**Comment by milseman** [comment]
It should. Pull does a fetch. Are you observing something different?

**Comment by weissi** [comment]
@milseman yes, I always need to `git fetch` everywhere otherwise I get `"$SHA is not a tree"`...

**Comment by weissi** [comment]
and if you manually go to that directory and try `git show $SHA` or `git log $SHA` it confirms that `$SHA` doesn't exist. After `git fetch` it all works!?

**Comment by milseman** [comment]
If you do a pull, does it still give that error? Is it possible that update-checkout is wrong here. Either way, I'm ok with this

**Comment by weissi** [comment]
@milseman sorry was already home. I'll try next time to do a manual pull.

**Pull request merged**
